apiVersion: v1
kind: Secret
metadata:
  name: shopping-list-secret
type: Opaque
data:
  mongo-uri: bW9uZ29kYjovL21hdGFuOlBhc3N3b3JkMUBzaG9wcGluZy1saXN0LW1vbmdvZGI6MjcwMTcvbXlkYj9hdXRoU291cmNlPW15ZGI=

# mongodb://matan:Password1@mongodb:27017/mydb?authSource=mydb

# mongodb://matan:Password1@shopping-list-mongodb:27017/mydb?authSource=mydb